version: "3.9"
services:
  api:
    image: golang:buster
    command: go run ./src/main.go
    working_dir: /home/app/api
    environment:
      - RIOT_API_KEY
    ports:
      - 4000:4000
    volumes:
      - ./api:/home/app/api
    networks:
      - leeg_internal

  kernel:
    image: merakianalytics/kernel:mongo
    ports:
      - 5000:8080
    environment:
      - RIOT_API_KEY
    depends_on:
      - mongo
    volumes:
    - ./kernel/etc/kernel-config.json:/opt/meraki/kernel-config.json
    networks:
      - leeg_internal

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 5001:8080
    environment:
      - API_URL=http://localhost:5000/lol/swagger.json
    depends_on:
      - kernel
    networks:
      - leeg_internal

  mongo:
    image: mongo:jessie
    networks:
      - leeg_internal

networks:
  leeg_internal:
    driver: bridge