version: "3.9"
services:
  web:
    image: node:latest
    command: ./start.sh
    working_dir: /home/app/web
    ports:
      - 8080:3000
    volumes:
      - ./web:/home/app/web

  api:
    image: golang:buster
    command: go run ./src/main.go
    working_dir: /home/app/api
    ports:
      - 4000:4000
    volumes:
      - ./api:/home/app/api

  kernel:
    image: merakianalytics/kernel:mongo
    ports:
      - 5000:8080
    environment:
      - RIOT_API_KEY
    depends_on:
      - mongo
    volumes:
    - ./kernel/etc/kernel-config.json:/opt/meraki/kernel-config.json

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 5001:8080
    environment:
      - API_URL=http://localhost:5000/lol/swagger.json
    depends_on:
      - kernel

  mongo:
    image: mongo:jessie