version: "3.9"
services:
  web:
    image: node:latest
    command: ./start.sh
    working_dir: /home/app/web
    ports:
      - 4200:3000
    volumes:
      - ./web:/home/app/web
    depends_on:
      - api

  api:
    image: node:latest
    command: ./start.sh
    working_dir: /home/app/api
    ports:
      - 4300:4000
    environment:
      - RIOT_API_KEY
      - MONGO_HOST
    volumes:
      - ./api:/home/app/api
    depends_on:
      - redis
      - mongo
      - rabbitmq
    networks:
      - backend

  redis:
    image: redis:buster
    volumes:
      - redis:/data
    networks:
      - backend

  mongo:
    image: mongo:jessie
    ports:
      - 4310:27017
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 4320:15672 # management UI - default credentials are guest:guest
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb: {}
  redis: {}
