version: "3.9"
services:
  web:
    image: node:latest
    command: ./start.sh
    working_dir: /home/app/web
    ports:
      - 4200:3000
    volumes:
      - ./web:/home/app/web
    depends_on:
      - api

  api:
    image: golang:buster
    command: ./start.sh
    working_dir: /home/app/api
    ports:
      - 4300:4000
    volumes:
      - ./api:/home/app/api
    depends_on:
      - kernel
      - mongo
    networks:
      - backend

  kernel:
    image: merakianalytics/kernel:mongo
    ports:
      - 4310:8080
    environment:
      - RIOT_API_KEY
    depends_on:
      - mongo
    volumes:
    - ./kernel/etc/kernel-config.json:/opt/meraki/kernel-config.json
    networks:
      - backend

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 4311:8080
    environment:
      - API_URL=http://localhost:4310/lol/swagger.json
    depends_on:
      - kernel

  mongo:
    image: mongo:jessie
    ports:
      - 4320:27017
    volumes:
      - mongodb:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 4330:15672 # management UI - default credentials are guest:guest
      - 4331:5672
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb: {}
